---
abstract: 'AnyEvent hiredis API'
author:
  - 'Whitney Jackson'
build_requires:
  Exporter: 0
  File::Which: 0
  FindBin: 0
  Test::Exception: 0
  Test::More: 0
  Test::TCP: 0
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Hiredis
requires:
  AnyEvent: 0
  Hiredis::Async: 0
  namespace::autoclean: 0
version: 0.01
